//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class card
    {
        [Key]
        public int card_id { get; set; }
        public string card_name { get; set; }
        public int card_type { get; set; }
        public int cost { get; set; }
    
        public virtual fighter fighter { get; set; }
        public virtual healing healing { get; set; }
        public virtual weapon weapon { get; set; }
    }
}
