//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class deck
    {
        [Key, Column(Order=0)]
        public int user_id { get; set; }
        [Key, Column(Order = 1)]
        public int deck_slot { get; set; }
        public string card_ids { get; set; }
        public string deck_name { get; set; }

        [InverseProperty("user_id")]
        [ForeignKey("user_id")]
        public virtual user user { get; set; }
    }
}
