//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class stardeckEntities : DbContext
    {
        public stardeckEntities()
            : base("name=stardeckEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<card> cards { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<deck> decks { get; set; }
        public virtual DbSet<fighter> fighters { get; set; }
        public virtual DbSet<healing> healings { get; set; }
        public virtual DbSet<match> matches { get; set; }
        public virtual DbSet<post> posts { get; set; }
        public virtual DbSet<user_profile> user_profile { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<weapon> weapons { get; set; }
    }
}
