//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.comments = new HashSet<comment>();
            this.decks = new HashSet<deck>();
            this.posts = new HashSet<post>();
        }
    
        public int user_id { get; set; }
        public string username { get; set; }
        public string profile_pic { get; set; }
        public string password { get; set; }
        public string user_email { get; set; }
        public string country { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
    
        public virtual ICollection<comment> comments { get; set; }
        public virtual ICollection<deck> decks { get; set; }
        public virtual ICollection<post> posts { get; set; }
        public virtual user_profile user_profile { get; set; }
    }
}
